### ISSUE TITLE
CSS not available on every route

### ISSUE THREAD

**Issue by servesh-chaturvedi** [gitdagray/mern_stack_course#2]
Hi Dave, thanks for this wonderful epic course. Just wanted to point out that the following CSS code for 404 page doesn't work on every route such as `/users/xyz` 
`<link rel="stylesheet" href="css/style.css" />`

This should also include a forward slash as follows:
`<link rel="stylesheet" href="/css/style.css" />`

**Comment by gitdagray** [comment]
Nice catch! To clarify for anyone reading, this note refers to the backend REST API code. We did set up a 404 page view for anyone requesting resources in the browser. 

The example given `/users/xyz` will actually provide an unauthorized JSON response when the project is complete. However, requesting something from the backend like `/dave/dave` will produce the HTML page without CSS as this issue indicated.
