### ISSUE TITLE
[Question] How to decode json content with backslashes

### ISSUE THREAD

**Issue by ht990332** [gitdagray/mern_stack_course#3]
Hello. In the mern stack tutorial, is there any way to encode json content with backslashes on the backend? for example, if a passowrd contains a backslash.

**Comment by gitdagray** [comment]
You could use a regex to escape those characters. I suggest preventing a backslash from being used in a password.

**Comment by ht990332** [comment]
Thanks. I know how to use regex (been using Linux for over two decades). But I'm failing to understand how to modify the req object.

**Comment by gitdagray** [comment]
This should be accomplished when the JSON is created. This is better than trying to work with malformed JSON sent from a request. If you get a JSON error on the server-side, you should catch that error and send a response to the client indicating status 400 Bad Request. You could customize the response message to say they provided malformed JSON.
