### ISSUE TITLE
Response Awaited

### ISSUE THREAD

**Issue by repo-by-anish** [gitdagray/mern_stack_course#8]
In the createNewPost codes stop running after line "const note = await Note.create({ user, title, text })" when sending post request using Postman.

**Comment by Moti-Velz** [comment]
I'm at the same place as you, it seems like there is a data structure problem to fix for mongoose to understand the data being sent in and cast it as an ObjectId. Have you found a solution ?

**Comment by repo-by-anish** [comment]
Not yet!

> I'm at the same place as you, it seems like there is a data structure problem to fix for mongoose to understand the data being sent in and cast it as an ObjectId. Have you found a solution ?

Not Yet!

**Comment by Moti-Velz** [comment]
Changing mongoose package to 6.5.0 fixed it for me

**Comment by repo-by-anish** [comment]
> 6.5.0

Yes it works. Thank You.
